WITH PATIENTS AS (
	SELECT DISTINCT
		ENCNTR_ALIAS.ENCNTR_ID,
		ENCOUNTER.PERSON_ID
	FROM
		ENCNTR_ALIAS,
		ENCOUNTER
	WHERE
	    ENCNTR_ALIAS.ALIAS IN @prompt('Enter value(s) for Alias','A',,Multi,Free,Persistent,,User:0)
		AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
		AND ENCNTR_ALIAS.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
), WEIGHTS AS (
	SELECT DISTINCT
		CLINICAL_EVENT.ENCNTR_ID,
		MAX(CLINICAL_EVENT.RESUlT_VAL) KEEP (DENSE_RANK FIRST ORDER BY CLINICAL_EVENT.EVENT_END_DT_TM, CLINICAL_EVENT.EVENT_ID) AS FIRST_WEIGHT,
		MAX(CLINICAL_EVENT.RESUlT_VAL) KEEP (DENSE_RANK LAST ORDER BY CLINICAL_EVENT.EVENT_END_DT_TM, CLINICAL_EVENT.EVENT_ID) AS LAST_WEIGHT
	FROM
		CLINICAL_EVENT,
		PATIENTS
	WHERE
		PATIENTS.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
		AND CLINICAL_EVENT.EVENT_CLASS_CD = 159 -- NUM
		AND PATIENTS.PERSON_ID = CLINICAL_EVENT.PERSON_ID
		AND CLINICAL_EVENT.EVENT_CD = 30107 -- Weight
		-- AND CLINICAL_EVENT.EVENT_END_DT_TM <= BENZOS.DISCH_DT_TM
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'	
		AND CLINICAL_EVENT.RESULT_UNITS_CD = 170 -- kg
	GROUP BY
		CLINICAL_EVENT.ENCNTR_ID
)

SELECT DISTINCT
	ENCOUNTER.ENCNTR_ID AS ENCOUNTER_ID,
	ENCNTR_ALIAS.ALIAS AS FIN,
    ENCOUNTER.DISCH_DT_TM - ENCOUNTER.REG_DT_TM AS LOS,
    TRUNC(pi_from_gmt(ENCOUNTER.REG_DT_TM, 'America/Chicago') - PERSON.BIRTH_DT_TM, 0) AS AGE_DAYS,
    TRUNC((pi_from_gmt(ENCOUNTER.REG_DT_TM, 'America/Chicago') - PERSON.BIRTH_DT_TM) / 365.25, 0) AS AGE_YEARS,
    pi_get_cv_display(PERSON.SEX_CD) AS SEX,
	WEIGHTS.FIRST_WEIGHT,
	WEIGHTS.LAST_WEIGHT
FROM
	ENCNTR_ALIAS,
	ENCOUNTER,
	PATIENTS,
	PERSON,
	WEIGHTS
WHERE
	PATIENTS.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
	AND ENCOUNTER.PERSON_ID = PERSON.PERSON_ID
	AND PATIENTS.ENCNTR_ID = ENCNTR_ALIAS.ENCNTR_ID
	AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
	AND PATIENTS.ENCNTR_ID = WEIGHTS.ENCNTR_ID(+)
