WITH DEXM_PTS AS (
	SELECT DISTINCT
		CLINICAL_EVENT.ENCNTR_ID
	FROM
		CLINICAL_EVENT,
		ENCNTR_LOC_HIST
	WHERE
		CLINICAL_EVENT.EVENT_CD = 37556709 -- dexmedetomidine
		AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN
			pi_to_gmt(
				TO_DATE(
					@Prompt('Enter begin date', 'D', , mono, free, persistent, {'01/01/1800 00:00:00'}, User:0), 
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				), 
				'CST'
			)
			AND pi_to_gmt(
				TO_DATE(
					@Prompt('Enter end date', 'D', , mono, free, persistent, {'01/01/1800 00:00:00'}, User:1), 
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				) - 1/86400, 
				'CST'
			)
		AND CLINICAL_EVENT.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
		AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
			SELECT MAX(ELH.TRANSACTION_DT_TM)
			FROM ENCNTR_LOC_HIST ELH
			WHERE
				CLINICAL_EVENT.ENCNTR_ID = ELH.ENCNTR_ID
				AND ELH.TRANSACTION_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		)
		AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD = 1101851 -- HC PICU
), CLON_PTS AS (
	SELECT DISTINCT
		CLINICAL_EVENT.ENCNTR_ID
	FROM
		CLINICAL_EVENT,
		ENCNTR_LOC_HIST
	WHERE
		CLINICAL_EVENT.EVENT_CD = 37556577 -- clonidine
		AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN
			pi_to_gmt(
				TO_DATE(
					@Prompt('Enter begin date', 'D', , mono, free, persistent, {'01/01/1800 00:00:00'}, User:0), 
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				), 
				'CST'
			)
			AND pi_to_gmt(
				TO_DATE(
					@Prompt('Enter end date', 'D', , mono, free, persistent, {'01/01/1800 00:00:00'}, User:1), 
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				) - 1/86400, 
				'CST'
			)
		AND CLINICAL_EVENT.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
		AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
			SELECT MAX(ELH.TRANSACTION_DT_TM)
			FROM ENCNTR_LOC_HIST ELH
			WHERE
				CLINICAL_EVENT.ENCNTR_ID = ELH.ENCNTR_ID
				AND ELH.TRANSACTION_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		)
		AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD = 1101851 -- HC PICU
), PATIENTS AS (
	SELECT * FROM DEXM_PTS
	
	MINUS
	
	SELECT * FROM CLON_PTS
)

SELECT DISTINCT
	PATIENTS.ENCNTR_ID AS ENCOUNTER_ID,
	pi_from_gmt(ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))) AS BEGIN_EFFECTIVE_DATETIME,
	pi_from_gmt(ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))) AS END_EFFECTIVE_DATETIME,
	pi_from_gmt(ENCNTR_LOC_HIST.TRANSACTION_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))) AS TRANSACTION_DATETIME,
	pi_get_cv_display(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD) AS NURSE_UNIT
FROM
	ENCNTR_LOC_HIST,
	PATIENTS
WHERE
	PATIENTS.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID

SELECT DISTINCT
	ENCOUNTER.ENCNTR_ID AS ENCOUNTER_ID,
	TO_CHAR(pi_from_gmt(ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))), 'YYYY-MM-DD"T"HH24:MI:SS') AS BEGIN_EFFECTIVE_DATETIME,
	TO_CHAR(pi_from_gmt(ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))), 'YYYY-MM-DD"T"HH24:MI:SS') AS END_EFFECTIVE_DATETIME,
	TO_CHAR(pi_from_gmt(ENCNTR_LOC_HIST.TRANSACTION_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))), 'YYYY-MM-DD"T"HH24:MI:SS') AS TRANSACTION_DATETIME,
	CV_NURSE_UNIT.DISPLAY AS NURSE_UNIT
FROM
    CODE_VALUE CV_NURSE_UNIT,
	ENCNTR_LOC_HIST,
	ENCOUNTER,
	(
        SELECT DISTINCT
            ENCOUNTER.ENCNTR_ID AS ENCOUNTER_ID
        FROM
            CLINICAL_EVENT,
        	ENCNTR_LOC_HIST,
            ENCOUNTER
        WHERE 
        	CLINICAL_EVENT.EVENT_CD = 37556709
        	AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31' 
        	AND (
        		CLINICAL_EVENT.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
        		AND CLINICAL_EVENT.PERSON_ID = ENCOUNTER.PERSON_ID
        		AND ENCOUNTER.ACTIVE_IND = 1
        		AND ENCOUNTER.LOC_FACILITY_CD = 3796
            )
            AND (
        		CLINICAL_EVENT.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
        		AND ENCNTR_LOC_HIST.ACTIVE_IND = 1
        		AND CLINICAL_EVENT.EVENT_END_DT_TM >= ENCNTR_LOC_HIST.TRANSACTION_DT_TM
        		AND (CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM)
        		AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
        			SELECT MAX(ELH.TRANSACTION_DT_TM)
        			FROM ENCNTR_LOC_HIST ELH
        			WHERE
        				CLINICAL_EVENT.ENCNTR_ID = ELH.ENCNTR_ID
        				AND ELH.ACTIVE_IND = 1
        				AND CLINICAL_EVENT.EVENT_END_DT_TM >= ELH.TRANSACTION_DT_TM
        		)
        		AND ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD = 1101851
        	)
        	AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN
				pi_to_gmt(
					TO_DATE(
						@Prompt('Enter begin date', 'D', , mono, free, persistent, {'01/01/1800 00:00:00'}, User:0), 
						pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
					), 
					'CST'
				)
				AND pi_to_gmt(
					TO_DATE(
						@Prompt('Enter end date', 'D', , mono, free, persistent, {'01/01/1800 00:00:00'}, User:1), 
						pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
					) - 1/86400, 
					'CST'
				)
        
        MINUS
        
        SELECT DISTINCT
            ENCOUNTER.ENCNTR_ID AS ENCOUNTER_ID
        FROM
            CLINICAL_EVENT,
        	ENCNTR_LOC_HIST,
            ENCOUNTER
        WHERE 
        	CLINICAL_EVENT.EVENT_CD = 37556577
        	AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31' 
        	AND (
        		CLINICAL_EVENT.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
        		AND CLINICAL_EVENT.PERSON_ID = ENCOUNTER.PERSON_ID
        		AND ENCOUNTER.ACTIVE_IND = 1
        		AND ENCOUNTER.LOC_FACILITY_CD = 3796
            )
            AND (
        		CLINICAL_EVENT.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
        		AND ENCNTR_LOC_HIST.ACTIVE_IND = 1
        		AND CLINICAL_EVENT.EVENT_END_DT_TM >= ENCNTR_LOC_HIST.TRANSACTION_DT_TM
        		AND (CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM)
        		AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
        			SELECT MAX(ELH.TRANSACTION_DT_TM)
        			FROM ENCNTR_LOC_HIST ELH
        			WHERE
        				CLINICAL_EVENT.ENCNTR_ID = ELH.ENCNTR_ID
        				AND ELH.ACTIVE_IND = 1
        				AND CLINICAL_EVENT.EVENT_END_DT_TM >= ELH.TRANSACTION_DT_TM
        		)
        		AND ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD = 1101851
        	)
        	AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN
				pi_to_gmt(
					TO_DATE(
						@Prompt('Enter begin date', 'D', , mono, free, persistent, {'01/01/1800 00:00:00'}, User:0), 
						pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
					), 
					'CST'
				)
				AND pi_to_gmt(
					TO_DATE(
						@Prompt('Enter end date', 'D', , mono, free, persistent, {'01/01/1800 00:00:00'}, User:1), 
						pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
					) - 1/86400, 
					'CST'
				)
	) ENCNTRS_DEXMED
WHERE
    ENCNTRS_DEXMED.ENCOUNTER_ID = ENCOUNTER.ENCNTR_ID
    AND ENCOUNTER.ACTIVE_IND = 1
    AND (
		ENCOUNTER.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
		AND ENCNTR_LOC_HIST.ACTIVE_IND = 1
		AND ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD = CV_NURSE_UNIT.CODE_VALUE
	)
