WITH PATIENTS AS (
	SELECT DISTINCT
		ENCNTR_ALIAS.ENCNTR_ID,
		ENCOUNTER.PERSON_ID
	FROM
		ENCNTR_ALIAS,
		ENCOUNTER
	WHERE
	    ENCNTR_ALIAS.ALIAS IN @prompt('Enter value(s) for Alias','A',,Multi,Free,Persistent,,User:0)
		AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
		AND ENCNTR_ALIAS.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
)

SELECT DISTINCT
	PATIENTS.ENCNTR_ID AS ENCOUNTER_ID,
	TO_CHAR(pi_from_gmt(CE_DATE_RESULT.RESULT_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))), 'YYYY-MM-DD"T"HH24:MI:SS') AS RESULT_DATETIME,
	pi_get_cv_display(CLINICAL_EVENT.EVENT_CD) AS EVENT
FROM
    CE_DATE_RESULT,
    CLINICAL_EVENT,
	PATIENTS
WHERE
	PATIENTS.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
	AND CLINICAL_EVENT.EVENT_CLASS_CD = 99985 -- DATE
	AND PATIENTS.PERSON_ID = CLINICAL_EVENT.PERSON_ID
	AND CLINICAL_EVENT.EVENT_CD IN (
		91538378, -- Vent Start Time
		91538829 -- Vent Stop Time
	)
	AND CLINICAL_EVENT.EVENT_ID = CE_DATE_RESULT.EVENT_ID
	AND CE_DATE_RESULT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
