---
title: "Exploratory Data Analysis"
author: "Brian Gulbis"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
    html_document:
        code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

```{r, message=FALSE}
library(tidyverse)
library(readxl)
library(lubridate)
library(edwr)
library(themebg)

dir_raw <- "../data/raw"

manual <- read_excel(
    "../data/external/manual_data.xlsx",
    sheet = "CAPD scores", 
    range = "A2:L628",
    # skip = 1,
    col_names = c(
        "patient.id", 
        "fin",
        "name", 
        "screen.date", 
        "time.day",
        "wat",
        "comfort.b",
        "capd.score",
        "match",
        "nurse.assess",
        "valid.score",
        "pos"
    ),
    col_types = c(
        "numeric",
        "text",
        "text",
        "date",
        "numeric",
        "numeric",
        "numeric",
        "numeric",
        "numeric",
        "numeric",
        "numeric",
        "numeric"
    )
) %>%
    filter(!is.na(fin)) %>%
    mutate_at("fin", as.character) %>%
    mutate_at("match", funs(. == 1))

capd_pos <- manual %>%
    filter(capd.score >= 9) %>%
    distinct(fin, screen.date) 

id_pts <- read_data(dir_raw, "id-fin", FALSE) %>%
    as.id()

demog <- read_data(dir_raw, "demographics", FALSE) %>%
    as.demographics(extras = list("age.days" = "Age- Days (At Admit)")) %>%
    mutate_at("age.days", as.numeric) %>%
    left_join(id_pts, by = "millennium.id")

# demog %>%
#     left_join(id_pts, by = "millennium.id") %>%
#     write.csv("data/external/demographics.csv", row.names = FALSE)

locations <- read_data(dir_raw, "locations", FALSE) %>%
    as.locations() %>%
    tidy_data()

measures <- read_data(dir_raw, "events-measures", FALSE) %>%
    as.events(order_var = FALSE)

visits <- read_data(dir_raw, "visits", FALSE) %>%
    as.visits() %>%
    select(-nurse.unit.admit) %>%
    distinct()

vent <- read_data(dir_raw, "vent-times", FALSE) %>%
    as.vent_times() %>%
    tidy_data(dc = visits)

meds_keep <- bind_rows(
    med_lookup("benzodiazepines"),
    med_lookup("narcotic analgesics"),
    med_class_lookup("propofol"),
    med_class_lookup("dexmedetomidine"),
    med_lookup("loop diuretics"),
    med_lookup("neuromuscular blocking agents"),
    med_class_lookup("melatonin"),
    med_lookup("anticholinergic antiemetics"),
    med_lookup("glucocorticoids"),
    med_lookup("antipsychotics")
) %>%
    distinct(med.name) %>%
    mutate_at("med.name", str_to_lower)
```

```{r}
raw_pts <- read_excel(
    "../data/raw/patient_list.xlsx", 
    skip = 1,
    col_names = c("patient.id", "fin", "name")
) %>%
    filter(!is.na(fin)) %>%
    mutate_at("fin", as.character)

pos_pts <- manual %>%
    filter(
        capd.score >= 9,
        match
    ) %>%
    distinct(fin) %>%
    mutate(group = "Positive")

neg_pts <- manual %>%
    anti_join(pos_pts, by = "fin") %>%
    distinct(fin) %>%
    mutate(group = "Negative")

data_patients <- raw_pts %>%
    left_join(
        bind_rows(pos_pts, neg_pts),
        by = "fin"
    ) %>%
    left_join(id_pts, by = "fin") 

# write.csv(
#     data_patients, 
#     "data/external/patient_groups.csv", 
#     row.names = FALSE
# )

valid <- manual %>%
    semi_join(pos_pts, by = "fin") %>%
    filter(valid.score >= 9) %>%
    distinct(fin)
```

```{r}

# pos capd >= 9
# comfort.b scores pos vs neg, median, iqr
# time wt-avg comfort.b for 5 days prior to capd score, compare across groups
# meds 5 days prior to capd score; time wt-dose compare across groups
# picu only

data_screen <- data_patients %>%
    left_join(capd_pos, by = "fin") %>%
    select(millennium.id, group, screen.date)

meds <- read_data(dir_raw, "meds-inpt", FALSE) %>%
    as.meds_inpt() %>%
    semi_join(meds_keep, by = c("med" = "med.name")) %>%
    filter(med.location == "HC PICU") 

meds_capd <- meds %>%
    left_join(data_screen, by = "millennium.id") %>%
    filter(
        !is.na(event.tag),
        (
            group == "Negative" |
                (
                    group == "Positive" &
                    floor_date(med.datetime, "day") >= screen.date - days(5) &
                    floor_date(med.datetime, "day") < screen.date
                )
        )
    ) 

```

## ICU Data

```{r, fig.cap="Distribution of PICU lenght of stay between groups. Outliers above 50 days are not shown."}
picu <- locations %>%
    filter(location == "HC PICU") %>%
    left_join(data_screen, by = "millennium.id") %>%
    distinct(millennium.id, unit.count, .keep_all = TRUE) %>%
    mutate_at("unit.length.stay", as.numeric) 

picu %>%
    ggplot(aes(x = group, y = unit.length.stay)) +
    geom_boxplot() +
    xlab(NULL) +
    ylab("Length of stay (days)") +
    coord_cartesian(ylim = c(0, 50)) +
    theme_bg()
```

```{r}
picu %>%
    group_by(group) %>%
    summarize_at(
        "unit.length.stay",
        funs(
            mean, 
            sd, 
            median, 
            q25 = quantile(., 0.25), 
            q75 = quantile(., 0.75),
            max,
            sum
        ),
        na.rm = TRUE
    ) %>%
    knitr::kable(
        digits = 1, 
        caption = "Distribution of PICU lenght of stay between"
    )
```


## Continuous Infusions

```{r, fig.cap="Distribution of infusion rates by medication. This includes all non-zero rates for all patients in the Negative group and non-zero rates for 5 days prior to Positive CAPD score."}
meds_capd %>%
    filter(med.rate > 0) %>%
    ggplot(aes(x = group, y = med.rate)) +
    geom_boxplot() +
    xlab(NULL) +
    ylab("Infusion Rate") +
    facet_wrap(~ med, scales = "free_y") +
    theme_bg()

```

```{r}
meds_capd %>%
    filter(med.rate > 0) %>%
    group_by(med, group) %>%
    summarize_at(
        "med.rate",
        funs(
            mean, 
            sd, 
            median, 
            q25 = quantile(., 0.25), 
            q75 = quantile(., 0.75),
            max,
            sum
        ),
        na.rm = TRUE
    ) %>%
    knitr::kable(
        digits = 1, 
        caption = "Distribution of infusion rates by medication"
    )

```


```{r, fig.cap="Distribution of the time-weighted infusion rate by medication. In this case, the time-weighted average infusion rate is calculated for each patient, and then the distribution of those averages is shown in the graph. Each patient contributes one data point rather than multiple data points as they do in the previous graph."}
meds_capd_sum <- meds_capd %>%
    calc_runtime() %>%
    summarize_data() %>%
    left_join(data_screen, by = "millennium.id") %>%
    distinct(millennium.id, med, drip.count, .keep_all = TRUE)

meds_capd_sum %>%
    ggplot(aes(x = group, y = time.wt.avg)) +
    geom_boxplot() +
    xlab(NULL) +
    ylab("Time-weighted infusion rate") +
    facet_wrap(~ med, scales = "free_y") +
    theme_bg()

```

```{r}
meds_capd_sum %>%
    group_by(med, group) %>%
    summarize_at(
        c("time.wt.avg"),
        funs(
            mean, 
            sd, 
            median, 
            q25 = quantile(., 0.25), 
            q75 = quantile(., 0.75)
        ),
        na.rm = TRUE
    ) %>%
    knitr::kable(
        digits = 1, 
        caption = "Distribution of time-weighted average infusion rates by medication"
    )

```

## Comfort B Scores

```{r}
comf_b <- read_data(dir_raw, "comfort", FALSE) %>%
    as.events(order_var = FALSE) %>%
    filter(!is.na(event.result))

comf_b_values <- comf_b %>%
    left_join(data_screen, by = "millennium.id") %>%
    filter(
        group == "Negative" |
            (
                group == "Positive" &
                floor_date(event.datetime, "day") >= screen.date - days(5) &
                floor_date(event.datetime, "day") < screen.date
            )
    ) %>%
    mutate_at("event.result", as.numeric) 
```

```{r, fig.cap="Distribution of Comfort B scores between groups. Includes all scores for Negative group and scores for 5 days prior to Positive CAPD score."}
comf_b_values %>%
    ggplot(aes(x = group, y = event.result)) +
    geom_boxplot() +
    xlab(NULL) +
    ylab("Comfort B Score") +
    theme_bg()
```

```{r}
comf_b_values %>%
    group_by(group) %>%
    summarize_at(
        "event.result",
        funs(
            mean, 
            sd, 
            median, 
            q25 = quantile(., 0.25), 
            q75 = quantile(., 0.75),
            max
        ),
        na.rm = TRUE
    ) %>%
    knitr::kable(digits = 1, caption = "Distribution of Comfort B scores")

```

```{r}
write.csv(
    meds_capd, 
    "../data/external/meds-continuous_all-rates.csv", 
    row.names = FALSE
)

write.csv(
    meds_capd_sum, 
    "../data/external/meds-continuous_summarized.csv", 
    row.names = FALSE
)

write.csv(
    comf_b_values,
    "../data/external/comfort-b_values.csv",
    row.names = FALSE
)
```

